working upgrade and generic signer
snowball-tools/snowball-ts-sdk pull request #17
Opened 2024-01-31 21:35 UTC by VPhung24

2024-02-01 22:02 UTC, ericlewis commented on src/auth/passkey/LitPasskey.ts
>  			debug: true,
should be configurable?

2024-02-01 22:04 UTC, ericlewis commented on src/snowball/Snowball.ts
>  			return Promise.reject(`authenticate failed ${error}`);
you don't need the resolve / reject here, you can rethrow error from the catch or simply don't try/catch for the same result (with the exception that you aren't rewriting the result)

2024-02-01 22:05 UTC, ericlewis commented on src/snowball/Snowball.ts
> +			if (!this.smartWallet) {
this check is appear a lot, maybe consider turning it into a function and using it that way.

2024-02-01 22:05 UTC, ericlewis requested changes
looks good. a few comments.

2024-02-01 22:57 UTC, VPhung24 commented on src/snowball/Snowball.ts
> +			if (!this.smartWallet) {
will do! meant to be a patch before the major rewrite (starting with the next pull request making each module its own package)

2024-02-02 17:05 UTC, ericlewis approved these changes

2024-02-02 20:57 UTC, merged

2024-02-05 21:17 UTC, VPhung24 commented
### Merge activity

* **Feb 5, 4:17 PM EST**: @VPhung24 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/snowball-tools/snowball-ts-sdk/17).