GNU header
snowball-tools/snowball-ts-sdk pull request #20
Opened 2024-02-02 01:47 UTC by VPhung24

2024-02-02 01:48 UTC, VPhung24 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/snowball-tools/snowball-ts-sdk/20?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* `main`
  * **#18** <a href="https://app.graphite.dev/github/pr/snowball-tools/snowball-ts-sdk/18?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **#17** <a href="https://app.graphite.dev/github/pr/snowball-tools/snowball-ts-sdk/17?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **#19** <a href="https://app.graphite.dev/github/pr/snowball-tools/snowball-ts-sdk/19?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **#20** <a href="https://app.graphite.dev/github/pr/snowball-tools/snowball-ts-sdk/20?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @VPhung24 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-02-05 15:53 UTC, ericlewis commented on LICENSE
> +    <one line to give the program's name and a brief idea of what it does.>
?

2024-02-05 15:54 UTC, ericlewis commented on packages/helpers/src/auth.ts
> + * (at your option) any later version.
uhhhh. we are distributing under the GPL 3.0 license?

2024-02-05 15:54 UTC, ericlewis requested changes
hmmm, I think our licensing might not be correct here.

2024-02-05 18:04 UTC, VPhung24 commented on LICENSE
> +    <one line to give the program's name and a brief idea of what it does.>
[GNUv3](https://www.gnu.org/licenses/gpl-3.0.en.html) LICENSE shouldn't be edited at all. It should be left as is

2024-02-05 18:04 UTC, VPhung24 commented on packages/helpers/src/auth.ts
> + * (at your option) any later version.
only the sdk. open to changing this

2024-02-05 18:13 UTC, VPhung24 commented on LICENSE
>  state the exclusion of warranty; and each file should have at least
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: lines 5 to 6]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->Reference: "Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed."<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/snowball-tools/snowball-ts-sdk/20?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-02-05 18:14 UTC, VPhung24 commented
> hmmm, I think our licensing might not be correct here.
> 
> 

Yeah, I need to add it to the readme -- I'll make the change but here's the start of it stating to not edit the file. I could be wrong. https://app.graphite.dev/github/pr/snowball-tools/snowball-ts-sdk/20/GNU-header#comment-PRRC_kwDOKLKkeM5YIvVs

2024-02-05 18:22 UTC, VPhung24 commented
added to readme: https://app.graphite.dev/github/pr/snowball-tools/snowball-ts-sdk/20/GNU-header#file-README.md

2024-02-05 21:15 UTC, ericlewis approved these changes
we can always relicense I suppose

2024-02-05 21:17 UTC, merged